Update optipng to v0.7.8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (C) 2008-2017 Cosmin Truta.
+# Copyright (C) 2008-2023 Cosmin Truta.
 #
 # This software is distributed under the zlib license.
 # Please see the accompanying LICENSE file.
@@ -8,9 +8,9 @@
 trap "rm -f conftest* core a.out; exit 1" 1 2 3 15
 
 LC_ALL=C
-export LC_ALL
+LANG=C
 LANGUAGE=C
-export LANGUAGE
+export LC_ALL LANG LANGUAGE
 
 prefix="${prefix-/usr/local}"
 exec_prefix="${exec_prefix-\$(prefix)}"
@@ -31,7 +31,11 @@ with_system_zlib=0
 with_preconfigured_libpng=1
 with_preconfigured_zlib=0
 
-unique_file=src/optipng/optipng.c
+toplevel_srcdir=`dirname "$0"`
+libpng_srcdir="$toplevel_srcdir/third_party/libpng"
+zlib_srcdir="$toplevel_srcdir/third_party/zlib"
+
+unique_file="./src/optipng/optipng.c"
 
 for arg in "$@"
 do
@@ -55,25 +59,25 @@ do
         ;;
     esac
     case "$option" in
-    -help | -hel | -he | -h )
+    -help | -hel | -he | -[h?] )
         echo "Usage:"
         echo "    $0 [options]"
         echo "Options:"
-        echo "    -h, -help               Show this help"
+        echo "    -?, -h, --help          Show this help"
         echo "Installation directories:"
-        echo "    -prefix=PREFIX          Install architecture-independent files in PREFIX"
+        echo "    --prefix=PREFIX         Install architecture-independent files in PREFIX"
         echo "                            [default: $prefix]"
-        echo "    -exec-prefix=EPREFIX    Install architecture-dependent files in EPREFIX"
+        echo "    --exec-prefix=EPREFIX   Install architecture-dependent files in EPREFIX"
         echo "                            [default: PREFIX]"
-        echo "    -bindir=DIR             Install executable in DIR [default: EPREFIX/bin]"
-        echo "    -mandir=DIR             Install manual in DIR [default: PREFIX/man]"
+        echo "    --bindir=DIR            Install executable in DIR [default: EPREFIX/bin]"
+        echo "    --mandir=DIR            Install manual in DIR [default: PREFIX/man]"
         echo "Optional features:"
-        echo "    -enable-debug           Enable debug build flags and run-time checks"
+        echo "    --enable-debug          Enable debug build flags and run-time checks"
         echo "Optional packages:"
-        echo "    -with-system-libs       Use all system-supplied libraries (details below)"
-        echo "    -with-system-libpng     Use the system-supplied libpng"
+        echo "    --with-system-libs      Use all system-supplied libraries (details below)"
+        echo "    --with-system-libpng    Use the system-supplied libpng"
         echo "                            [default: false]"
-        echo "    -with-system-zlib       Use the system-supplied zlib"
+        echo "    --with-system-zlib      Use the system-supplied zlib"
         echo "                            [default: with-system-libpng]"
         echo "Environment variables:"
         echo "    CC                      C compiler command"
@@ -121,10 +125,10 @@ do
     -mandir=* | -mandi=* | -mand=* | -man=* | -ma=* | -m=* )
         mandir="$optarg"
         ;;
-    -enable-debug )
+    -enable-debug | -enable-debu | -enable-deb | -enable-de | -enable-d )
         enable_debug=1
         ;;
-    -disable-debug )
+    -disable-debug | -disable-debu | -disable-deb | -disable-de | -disable-d )
         enable_debug=0
         ;;
     -with-system-libs )
@@ -152,24 +156,26 @@ do
         with_system_libpng=0
         ;;
     * )
-        echo "$0: error: unknown option: $arg"
-        echo "Type \"$0 -help\" for help"
+        echo "$0: error: unknown option: '$arg'"
+        echo "Type \"$0 --help\" for help"
         exit 64  # EX_USAGE
         ;;
     esac
 done
 
-if test ! -f "$0"
-then
+test -f "$0" || {
     echo "$0: error: cannot find myself; rerun with an absolute file name"
     exit 1
-fi
+}
 
-if test ! -r "$unique_file"
+if test "$with_system_zlib" -eq 0 || test "$with_system_libpng" -eq 0
 then
-    echo "$0: error: cannot find: $unique_file"
-    echo "$0: note: building outside the source directory tree is not supported"
-    exit 1
+    test -r "$unique_file" || {
+        echo "$0: error: no such file: '$unique_file'"
+        echo "$0: note: out-of-tree builds are not supported in this configuration"
+        echo "$0: note: please run: 'cd $toplevel_srcdir && ./configure${*:+ $*}'"
+        exit 1
+    }
 fi
 
 test=conftest$$
@@ -181,7 +187,7 @@ gccish=0
 case "$cc" in
 *gcc* | *clang* )
     echo "Checking for $cc..."
-    if ($cc -c $cflags $test.c) 2>/dev/null
+    if ("$cc" -c $cflags $test.c) 2>/dev/null
     then
         gccish=1
     fi
@@ -193,7 +199,7 @@ rm -f $test.c $test.o
 if test "$gccish" -ne 0
 then
     CC="${CC-$cc}"
-    CFLAGS="${CFLAGS--O2 -Wall -Wextra}"
+    CFLAGS="${CFLAGS--O2 -Wall -Wextra -Wundef}"
 else
     CC="${CC-cc}"
     CFLAGS="${CFLAGS--O}"
@@ -214,18 +220,18 @@ then
     test=conftest$$
 cat > $test.c <<EOM
 #include <png.h>
-#if PNG_LIBPNG_VER < 10209
-#error This program requires libpng version 1.2.9 or higher
+#if PNG_LIBPNG_VER < 10635
+#error This program requires libpng version 1.6.35 or higher
 #endif
 int dummy;
 EOM
-    ($CC -c $CPPFLAGS $CFLAGS $test.c) 2>/dev/null
+    ("$CC" -c $CPPFLAGS $CFLAGS $test.c) 2>/dev/null
     status=$?
     rm -f $test.c $test.o
     if test $status -ne 0
     then
         echo "$0: error: missing libpng or incorrect libpng version"
-        echo "$0: note: libpng version 1.2.9 or higher is required"
+        echo "$0: note: libpng version 1.6.35 or higher is required"
         exit 1
     fi
 else
@@ -235,11 +241,10 @@ else
     then
         echo "Using pre-configured libpng..."
         libpng_preconfig_makefile=scripts/makefile.gcc
-        if test ! -f "src/libpng/$libpng_preconfig_makefile"
-        then
-            echo "$0: warning: cannot find: src/libpng/$libpng_preconfig_makefile"
-            with_preconfigured_libpng=0
-        fi
+        test -f "$libpng_srcdir/$libpng_preconfig_makefile" || {
+            echo "$0: error: no such file: '$libpng_srcdir/$libpng_preconfig_makefile'"
+            exit 1
+        }
     fi
     if test "$with_preconfigured_libpng" -ne 0
     then
@@ -298,19 +303,17 @@ else
             "
         fi
         sed "$sed_preconfig_libpng" \
-            src/libpng/$libpng_preconfig_makefile > src/libpng/Makefile
+            "$libpng_srcdir/$libpng_preconfig_makefile" > "$libpng_srcdir/Makefile"
         LIBPNG_MK=Makefile
         # The pre-configured makefiles in libpng don't do distclean.
         LIBPNG_DISTCLEAN="clean"
         LIBPNG_DISTCLEAN_XCMD="\$(RM_F) \$(LIBPNG_MK)"
     else
         echo "Configuring libpng..."
-        (cd src/libpng && ./configure)
-        if test $? -ne 0
-        then
+        (cd "$libpng_srcdir" && ./configure --enable-static --disable-shared) || {
             echo "$0: error: could not configure: libpng"
             exit 1
-        fi
+        }
     fi
 fi
 
@@ -322,57 +325,66 @@ then
     test=conftest$$
 cat > $test.c <<EOM
 #include <zlib.h>
-#if ZLIB_VERNUM < 0x1210
-#error This program requires zlib version 1.2.1 or higher.
+#if ZLIB_VERNUM < 0x1280
+#error This program requires zlib version 1.2.8 or higher.
 #endif
 int dummy;
 EOM
-    ($CC -c $CPPFLAGS $CFLAGS $test.c) 2>/dev/null
+    ("$CC" -c $CPPFLAGS $CFLAGS $test.c) 2>/dev/null
     status=$?
     rm -f $test.c $test.o
     if test $status -ne 0
     then
         echo "$0: error: missing zlib or incorrect zlib version"
-        echo "$0: note: zlib version 1.2.1 or higher is required"
+        echo "$0: note: zlib version 1.2.8 or higher is required"
         exit 1
     fi
 else
     USE_SYSTEM_ZLIB_TRUE="#"
     USE_SYSTEM_ZLIB_FALSE=""
-    case `(uname -s) 2>/dev/null || echo unknown` in
-    mingw* | MINGW* | windows* | WINDOWS* )
-        with_preconfigured_zlib=1
+    ZLIB_MK=Makefile
+    case "$cc" in
+    *mingw*-cc* | *mingw*-gcc* )
         ZLIB_MK=win32/Makefile.gcc
-        # This pre-configured makefile doesn't do distclean.
-        ZLIB_DISTCLEAN=clean
         ;;
-    *djgpp | *DJGPP | *dos | *DOS )
-        with_preconfigured_zlib=1
+    *djgpp*-cc* | *djgpp*-gcc* )
         ZLIB_MK=msdos/Makefile.dj2
-        # This pre-configured makefile doesn't do distclean.
+        ;;
+    * )
+        case `(uname -s) 2>/dev/null || echo unknown` in
+        mingw* | MINGW* | MSYS* | windows* | WINDOWS* )
+            ZLIB_MK=win32/Makefile.gcc
+            ;;
+        *djgpp | *DJGPP | *dos | *DOS )
+            ZLIB_MK=msdos/Makefile.dj2
+            ;;
+        esac
+        ;;
+    esac
+    case "$ZLIB_MK" in
+    win32/Makefile.gcc | msdos/Makefile.dj2 )
+        with_preconfigured_zlib=1
+        # These pre-configured makefiles do not have the distclean target.
         ZLIB_DISTCLEAN=clean
         ;;
     * )
         with_preconfigured_zlib=0
-        ZLIB_MK=Makefile
         ZLIB_DISTCLEAN=distclean
+        ;;
     esac
     if test "$with_preconfigured_zlib" -ne 0
     then
         echo "Using pre-configured zlib..."
-        if test ! -f "src/zlib/$ZLIB_MK"
-        then
-            echo "$0: error: cannot find: src/zlib/$ZLIB_MK"
+        test -f "$zlib_srcdir/$ZLIB_MK" || {
+            echo "$0: error: no such file: '$zlib_srcdir/$ZLIB_MK'"
             exit 1
-        fi
+        }
     else
         echo "Configuring zlib..."
-        (cd src/zlib && ./configure --static)
-        if test $? -ne 0
-        then
+        (cd "$zlib_srcdir" && ./configure --static) || {
             echo "$0: error: could not configure: zlib"
             exit 1
-        fi
+        }
     fi
 fi
 
@@ -412,16 +424,18 @@ sed_config="
     s| *\$||
 "
 
-for makefile in \
-    ./Makefile \
-    src/Makefile \
-    src/gifread/Makefile \
-    src/minitiff/Makefile \
-    src/opngreduc/Makefile \
-    src/optipng/Makefile \
-    src/optipng/man/Makefile \
-    src/pngxtern/Makefile \
-    src/pnmio/Makefile
+for subdir in \
+    . \
+    ./src \
+    ./src/gifread \
+    ./src/minitiff \
+    ./src/opngreduc \
+    ./src/optipng \
+    ./src/optipng/man \
+    ./src/pngxtern \
+    ./src/pnmio
 do
-    sed "$sed_config" $makefile.in > $makefile
+    test -d "$subdir" || mkdir -p "$subdir"
+    sed "$sed_config" \
+        "$toplevel_srcdir/$subdir/Makefile.in" > "$subdir/Makefile"
 done
